#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 

bspc config border_width         2
bspc config window_gap           2

#Colors
bspc config normal_border_color		  "#4c566a"
bspc config active_border_color	          "#d75f5f"
bspc config focused_border_color	  "#add8e6"
#bspc config presel_feedback_color	  "#5e81ac"
#bspc config urgent_border_color 	  "#dd2727"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Opera desktop='^2'
bspc rule -a firefox desktop='^2' focus = on
bspc rule -a Code desktop='^4'
#bspc rule -a Alacritty desktop='^1'
#bspc rule -a Org.gnome.Nautilus desktop='^3'
